
#include <Arduino.h>
#include "Config.h"

#ifndef PINDEFINITIONS_H
#define PINDEFINITIONS_H

#define SENSOR_COUNT 12
#define NUM_LEDS 6

#define LOAD_PIN GPIO_NUM_27
#define CLOCK_ENABLE_PIN GPIO_NUM_4
#define DATA_PIN GPIO_NUM_17
#define CLOCK_PIN GPIO_NUM_16

#define AIN2 GPIO_NUM_25
#define AIN1 GPIO_NUM_26
#define BIN2 GPIO_NUM_32
#define BIN1 GPIO_NUM_33
#define PWMA GPIO_NUM_19
#define PWMB GPIO_NUM_18

#if REVERSE_MOTOR_POLARITY == 1

#define LEFT_MOTOR_PIN_1 GPIO_NUM_26
#define LEFT_MOTOR_PIN_2 GPIO_NUM_25

#define RIGHT_MOTOR_PIN_1 GPIO_NUM_33
#define RIGHT_MOTOR_PIN_2 GPIO_NUM_32

#else

#define LEFT_MOTOR_PIN_2 GPIO_NUM_26
#define LEFT_MOTOR_PIN_1 GPIO_NUM_25

#define RIGHT_MOTOR_PIN_2 GPIO_NUM_33
#define RIGHT_MOTOR_PIN_1 GPIO_NUM_32

#endif

#define LEFT_MOTOR_PWM_PIN GPIO_NUM_19
#define RIGHT_MOTOR_PWM_PIN GPIO_NUM_18

#define BLUE_LED GPIO_NUM_2
#define BUZZER GPIO_NUM_12
#define NEOPIXEL_LED_PIN GPIO_NUM_23

#endif
